[package]
name = "addresses"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.9"
ic-cdk = "0.13"
ic-cdk-timers = "0.7"
ic-cdk-macros = "0.8"  
ic-stable-structures = "0.6.5"
serde = "1.0.207"
serde_json = "1.0"